[package]
name = "ex_impl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[dependencies]
heapless = "0.7"

[dependencies.nom]
version = "7.1"
default-features = false
